version: "3"
services:
    api:
        image: "mpltr/php-apache-laravel:8.0_14.x"
        volumes:
            - ./api:/var/www/html
        ports:
            - "8080:80"
        # env_file: .env
        environment:
            - DB_USERNAME=postgres
            - DB_HOST=database-fpl.cftzexv4qexe.eu-west-1.rds.amazonaws.com
            - DB_DATABASE=postgres
            - DB_PASSWORD=localpass
            - APP_DEBUG=true
    # postgres:
    #     image: postgres:12.11
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         POSTGRES_PASSWORD: local
    #     volumes:
    #         - ./db:/var/lib/postgresql/data
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        ports:
            - "3000:3000"
