version: '3'
services:
  api:
    image: 'mpltr/php-apache-laravel:7.4_14.x'
    volumes:
      - ./api:/var/www/html
    ports:
      - '8080:80'
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=postgres
      - DB_DATABASE=postgres
      - DB_PASSWORD=local
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: local
    volumes:
      - ./db:/var/lib/postgresql/data
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "3000:3000"