version: '3'
services:
  api:
    image: 'mpltr/php-apache-laravel:7.4_14.x'
    volumes:
      - ./api:/var/www/html
    ports:
      - '8080:80'
    environment:
      - DB_USERNAME=postgres
      - DB_HOST=postgres
      - DB_DATABASE=postgres
      - DB_PASSWORD=local
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: local
    volumes:
      - ./db:/var/lib/postgresql/data
